services:
  backend1:
    build: .
    environment:
      - NAME=Backend 1

  backend2:
    build: .
    environment:
      - NAME=Backend 2

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    command: ["node", "worker/worker.js"]
    depends_on:
      - redis
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
